config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_scope :admin do
  get "/admin" => "devise/sessions#new"
  end
  resources :pictures
  resources :places
  get '/le-parc' => 'static_pages#parc'
  get '/la-maison' => 'static_pages#maison'
  get '/le-chalet' => 'static_pages#chalet'
  get '/le-port' => 'static_pages#port'
  get '/la-dépendance' => 'static_pages#dependance'
  get 'home_page' => 'home_page#home'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "places#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  after_create :welcome_send

  def welcome_send
    AdminMailer.welcome_email(self).deliver_now
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :place, optional: true
  has_one_attached :image

  validates :image, presence: true, blob: { content_type: :image, size_range: 5..(500.kilobytes) }
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :pictures
  has_one_attached :main_picture

    validates :main_picture, presence: true, blob: { content_type: :image, size_range: 5..(500.kilobytes) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, only: %i[ new edit update destroy ]

  # GET /pictures or /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1 or /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @place = Place.all
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures or /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: "La photo a bien été créée." }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1 or /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: "La photo a bien été mise à jour." }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1 or /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to request.referrer, notice: "La photo a bien été détruite." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def picture_params
      params.require(:picture).permit(:image, :caption, :place_id)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, only: %i[ new edit update destroy ]

  # GET /places or /places.json
  def index
    @places = Place.order('created_at')
  end

  # GET /places/1 or /places/1.json
  def show
    @pictures = @place.pictures
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places or /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to places_path, notice: "Place was successfully created." }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1 or /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to places_path, notice: "Place was successfully updated." }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1 or /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: "Place was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:main_picture, :head, :subhead, :description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top myNav">
  <div class="container">
    <a class="corner" href="/">
    <h4 class="my-3" style="color: white !important;">RETOUR À LA PAGE PRINCIPALE</h4>
  </a>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Les Andelys</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <script src="https://kit.fontawesome.com/82779c9172.js" crossorigin="anonymous"></script>

  <!-- Favicon-->
  <link rel="icon" type="image/x-icon" href="startbootstrap-agency-gh-pages/assets/favicon.ico" />

  <!-- Google fonts-->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
  <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
  <!-- Core theme CSS (includes Bootstrap)-->
</head>

<body id="page-top">
  <% unless action_name == "index" && controller_name == "places" %>
  <section class="page-section bg-light">
    <%= render 'layouts/navbar' %>
    <% end %>
    <%= yield %>
  </section>
</body>

<footer>
  <!-- Bootstrap core JS-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Core theme JS-->
  <script src="javascripts/scripts.js"></script>
  <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
  <!-- * *                               SB Forms JS                               * *-->
  <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
  <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
  <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</footer>
</html>

app/views/pictures/_form.html.erb
<div class="container">
  <%= form_with(model: picture, local: true) do |form| %>
  <% if picture.errors.any? %>
  <div id="error_explanation">
    <% picture.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
  </div>
  <% end %>
  <form>
    <div class="form-group">
      <label for="form-image">Photo</label>
      <%= form.file_field :image, class: "form-control", id: "form-image" %>
      <br>
      <label for="form-caption">Titre</label>
      <%= form.text_field :caption, class: "form-control", id: "form-caption" %>
      <br>
      <label for="form-place">Atribuer la photo à l'étiquette : </label>
      <%= form.collection_select(:place_id, Place.all, :id, :head, {:include_blank=>'Choisir'}) %>
      <br><br>
      <div class="actions">
        <%= form.submit "Valider", class: "btn btn-primary btn-xl text-uppercase" %>
      </div>
    </div>
  </form>
  <% end %>
</div>

app/views/pictures/edit.html.erb
<div class="container">
  <h1>Modifier la photo</h1>
</div>
<br>

<div class="container">
  <%= form_with(model: @picture, local: true) do |form| %>
  <% if @picture.errors.any? %>
  <div id="error_explanation">
    <% @picture.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
  </div>
  <% end %>
  <form>
    <div class="form-group">
      <label for="form-image">Photo</label>
      <%= form.file_field :image, id: "form-image", style:"display:none;" %>
      <label for="form-image", class="form-control">Changer la photo</label>
      <br>
      <label for="form-caption">Titre</label>
      <%= form.text_field :caption, class: "form-control", id: "form-caption" %>
      <br>
      <label for="form-place">Attribuer la photo à l'étiquette : </label>
      <%= form.collection_select(:place_id, Place.all, :id, :head, {:include_blank=>'Choisir'}) %>
      <br><br>
      <div class="actions">
        <%= form.submit "Valider", class: "btn btn-primary btn-xl text-uppercase" %>
      </div>
    </div>
  </form>
  <% end %>
</div>

app/views/pictures/index.html.erb
<% if admin_signed_in? %>
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Caption</th>
      <th>Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
    <tr>
      <td><%= image_tag picture.image%></td>
      <td><%= picture.caption %></td>
      <td><%= picture.place.try(:head) %></td>
      <td><%= link_to 'Show', picture %></td>
      <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
      <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>
<%else%>
<p class="text-center">Il n'y a rien par ici !</p>
<%end%>

app/views/pictures/new.html.erb
<% if admin_signed_in? %>
<div class="container">
  <h1>Nouvelle photo</h1>
</div>
<br>

<%= render 'form', picture: @picture %>
<% else %>
<% end %>

app/views/pictures/show.html.erb
<% if admin_signed_in? %>
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <div class="modal-body">
        <%=image_tag @picture.image, :class => "img-fluid d-block mx-auto", :alt => @picture.caption%>
        <h2 class="text-uppercase text-center"><%= @picture.caption %></h2>
        <%= link_to 'Modifier', edit_picture_path(@picture) %> - <%=link_to "Nouvelle photo", new_picture_path%>
      </div>
    </div>
  </div>
</div>
<% else redirect path %>
<% end %>

app/views/places/_form.html.erb
<div class="container">
  <%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
  <div id="error_explanation">
    <% place.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
  </div>
  <% end %>
  <form>
    <div class="form-group">
      <label for="form-main-picture">Photo principale</label>
      <%= form.file_field :main_picture, class: "form-control", id: "form-main-picture" %>
      <br>
      <label for="form-head">Titre</label>
      <%= form.text_field :head, class: "form-control", id: "form-head" %>
      <br>
      <label for="form-subhead">Sous-titre</label>
      <%= form.text_field :subhead, class: "form-control", id: "form-subhead" %>
      <br>
      <label for="form-description">Description</label>
      <%= form.text_area :description, class: "form-control", id: "form-description", rows: "3" %>
      <br>
      <div class="actions">
        <%= form.submit "Valider", class: "btn btn-primary btn-xl text-uppercase" %>
      </div>
    </div>
  </form>
  <% end %>
</div>

app/views/places/_placedescription.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <div class="modal-body">
        <!-- Project details-->
        <h2 class="text-uppercase"><%= @places.head %></h2>
        <p class="item-intro text-muted"><%= @places.subhead %></p>
        <img class="img-fluid d-block mx-auto" src="<%= @place.main_picture %>" />
        <div>
          <p><%= @places.description %></p>
        </div>
        <div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/places/edit.html.erb
<div class="container">
  <h1>Modifier l'étiquette</h1>
</div>
<br>

<div class="container">
  <%= form_with(model: @place, local: true) do |form| %>
  <% if @place.errors.any? %>
  <div id="error_explanation">
    <% @place.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
  </div>
  <% end %>
  <form>
    <div class="form-group">
      <label for="form-main-picture">Photo principale</label>
      <%= form.file_field :main_picture, id: "form-main-picture", style:"display:none;" %>
      <label for="form-main-picture", class="form-control">Changer la photo</label>
      <br>
      <label for="form-head">Titre</label>
      <%= form.text_field :head, class: "form-control", id: "form-head" %>
      <br>
      <label for="form-subhead">Sous-titre</label>
      <%= form.text_field :subhead, class: "form-control", id: "form-subhead" %>
      <br>
      <label for="form-description">Description</label>
      <%= form.text_area :description, class: "form-control", id: "form-description", rows: "3" %>
      <br>
      <div class="actions">
        <%= form.submit "Valider", class: "btn btn-primary btn-xl text-uppercase" %>
      </div>
    </div>
  </form>
  <% end %>
</div>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
  <div class="container">
    <h4 class="my-3" style="color: white;">A VENDRE ! - 750 000 €</h4>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars ms-1"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
        <%if admin_signed_in?%>
        <li class="nav-item"><%=link_to "Se déconnecter", destroy_admin_session_path, :method => :delete, class:"nav-link"%></li>
        <li class="nav-item"><%=link_to "Modifier mes identifiants", edit_admin_registration_path(current_admin.id), class:"nav-link"%></li>
        <%else%>
        <li class="nav-item"><a class="nav-link" href="#portfolio">Explorer la propriété</a></li>
        <li class="nav-item"><a class="nav-link" href="#contact">Nous contacter</a></li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>
<!-- En tête-->
<header class="masthead">
  <div class="container">
    <div class="masthead-subheading">Maison d'architecte avec port privatif au bord de la Seine <br>Eure en Normandie</div>
    <div class="masthead-heading text-uppercase">Un bien d'exception</div>
    <a class="btn btn-primary btn-xl text-uppercase" href="#portfolio">En savoir plus</a>
  </div>
</header>

<!-- Portfolio Grid-->
<section class="page-section bg-light" id="portfolio">
  <div class="container">
    <div class="text-center">
      <h2 class="section-heading text-uppercase">Explorer la propriété</h2>
      <h3 class="section-subheading">Vous avez un (ou des) bateau(x) , vous aimez la voile, vous avez un projet de reconversion professionnelle, une envie de changement de vie ? <br>
      cette propriété est parfaite pour cela !</h3><h3 class="section-subheading text-muted"><strong>L'adresse</strong> <br>5 route de Muids<br>Le Val Saint Martin<br>27700 Les Andelys</h3>
    </div>
    <div class="container">
      <div class="row">
        <div class="col col-lg-3">
        </div>
        <% if admin_signed_in? %>
        <div class="col col-lg-3">
          <div class="text-center">
            <a class="btn btn-primary btn-xl text-uppercase" href="places/new">Nouvelle étiquette</a>
          </div>
        </div>
        <div class="col col-lg-3">
          <div class="text-center">
            <a class="btn btn-primary btn-xl text-uppercase" href="pictures/new">Nouvelle photo</a>
          </div>
        </div>
        <div class="col col-lg-3">
        </div>
      </div>
    </div>
    <br><br><br>
    <% else %>
    <% end %>
    <div class="row">
      <div class="col-lg-4 col-sm-6 mb-4">
        <% @places.each do |place| %>
        <div class="portfolio-item">
          <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal<%= place.id %>">
            <div class="portfolio-hover">
              <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
            </div>
            <%if place.main_picture.attached?%>
            <%= image_tag place.main_picture, :class => "img-fluid", :alt => place.head%>
            <%else%>
            <%end%>
          </a>
          <a class="paragraph-link" data-bs-toggle="modal" href="#portfolioModal<%= place.id %>">
            <div class="portfolio-caption">
              <div class="portfolio-caption-heading"><%= place.head %></div>
              <div class="portfolio-caption-subheading text-muted"><%= place.subhead %></div>
              <% if admin_signed_in? %>
              <td><%= link_to 'Modifier', edit_place_path(place) %></td>
              <td><%= link_to 'Supprimer', place, method: :delete, data: { confirm: 'Supprimer ?' } %></td>
              <% else %>
              <% end %>
            </div>
          </a>
        </div>
      </div>
      <!-- Portfolio Modals-->
      <div class="col-lg-4 col-sm-6 mb-4">
        <div class="portfolio-modal modal fade" id="portfolioModal<%= place.id %>" tabindex="-1" role="dialog" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="close-modal" data-bs-dismiss="modal"><img src="startbootstrap-agency-gh-pages/assets/img/close-icon.svg" alt="Close modal" /></div>
              <div class="container">
                <div class="row justify-content-center">
                  <div class="col-lg-8">
                    <div class="modal-body">
                      <!-- Project details-->
                      <h2 class="text-uppercase"><%= place.head %></h2>
                      <p class="item-intro text-muted"><%= place.subhead %></p>
                      <%if place.main_picture.attached?%>
                      <%= image_tag place.main_picture, :class => "img-fluid d-block mx-auto", :alt => place.head%>
                      <%else%>
                      <%end%>
                      <div>
                        <p><%= place.description %></p>
                        <% if admin_signed_in? %>
                        <td><%= link_to 'Modifier', edit_place_path(place) %></td>
                        <td><%= link_to 'Supprimer', place, method: :delete, data: { confirm: 'Supprimer ?' } %></td>
                        <% else %>
                        <% end %>
                      </div>
                      <br>
                      <div>
                        <%= link_to '<i class="fas fa-camera"></i> Voir plus de photos'.html_safe, place, class:"btn btn-primary btn-xl text-uppercase" %>
                      </div>
                      <br>
                      <div>
                        <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">
                          <i class="fas fa-times me-1"></i>
                          Fermer la fenêtre
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</section>
<section class="page-section" id="contact">
  <div class="container">
    <div class="text-center">
      <h2 class="section-heading text-uppercase">Nous contacter</h2>
      <h3 class="section-subheading text-muted" style="color: white;">Contactez-nous pour toute question ou pour organiser une visite</h3>
      <a class="btn btn-primary btn-xl text-uppercase" href="mailto:sciprlduvalsaintmartin@orange.fr">
        <i class="far fa-paper-plane"></i>
        Envoyer un mail
      </a>
    </div>
  </div>
</section>

app/views/places/new.html.erb
<div class="container">
  <h1>Nouvelle étiquette</h1>
</div>
<br>

<div class="container">
  <%= form_with(model: @place, local: true) do |form| %>
  <% if @place.errors.any? %>
  <div id="error_explanation">
    <% @place.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
  </div>
  <% end %>
  <form>
    <div class="form-group">
      <label for="form-main-picture">Photo principale</label>
      <%= form.file_field :main_picture, class: "form-control", id: "form-main-picture" %>
      <br>
      <label for="form-head">Titre</label>
      <%= form.text_field :head, class: "form-control", id: "form-head" %>
      <br>
      <label for="form-subhead">Sous-titre</label>
      <%= form.text_field :subhead, class: "form-control", id: "form-subhead" %>
      <br>
      <label for="form-description">Description</label>
      <%= form.text_area :description, class: "form-control", id: "form-description", rows: "3" %>
      <br>
      <div class="actions">
        <%= form.submit "Valider", class: "btn btn-primary btn-xl text-uppercase" %>
      </div>
    </div>
  </form>
  <% end %>
</div>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>


<!-- Project details-->
<h2 class="text-center section-heading text-uppercase"><%= @place.head %></h2>

<%if @pictures.empty?%>
<br>
<br>
<br>
  <% if admin_signed_in? %>
<div class="col col-lg-12">
  <div class="text-center">
    <%=link_to "Nouvelle photo", new_picture_path, class:"nbtn btn-primary btn-xl text-uppercase"%>
  </div>
</div>
  <% else %>
<p class="text-center">Pas encore de photos, cela devrait bientôt arriver !</p>
  <% end %>
<% else %>
<div class="container" style="width: 60%">
  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <% @pictures.each_with_index do |picture, i| %>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="<%= i %>" class="<% if i == 0 %> active <% end %>" aria-current="true" aria-label="Slide #{i)">
      </button>
      <% end %>
    </div>

    <div class="carousel-inner">
      <% @pictures.each_with_index do |picture, i| %>
      <div class="carousel-item <% if i == 0 %>active<% end %>">
        <%= image_tag picture.image, :class => "d-block w-100", :alt => picture.caption%>
        <div class="carousel-caption d-none d-md-block">
          <h4><%= picture.caption %></h4>
          <div class="portfolio-caption-subheading">
            <% if admin_signed_in? %>
            <%= link_to 'Modifier', edit_picture_path(picture) %> -
            <%= link_to 'Supprimer', picture, method: :delete, data: { confirm: 'Supprimer ?' } %> - <%=link_to "Nouvelle photo", new_picture_path%>
            <% else %>
            <% end %>
          </div>
          <p></p>
        </div>
        <tr>
        </tr>
      </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Précédent</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Suivant</span>
    </button>
  </div>
</div>

<%end%>

app/views/static_pages/chalet.html.erb
<section class="page-section bg-light">
  <div class="container" style="width: 60%">
  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://res.cloudinary.com/felicie/image/upload/v1638390794/LesAndelys/Le%20chalet/1996463227577533827_copie_oji117.jpg" class="d-block w-100" alt="vu du côté">
      <div class="carousel-caption d-none d-md-block">
        <h4>Un chalet en pleine nature !</h4>
        <p></p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/felicie/image/upload/v1638390792/LesAndelys/Le%20chalet/IMG_3647_g4xbnz.jpg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Vue de derrière</h5>
        <p></p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/felicie/image/upload/v1638390792/LesAndelys/Le%20chalet/plan_chalet_qnnoxz.jpg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Le plan</h5>
        <p></p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Précédent</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Suivant</span>
  </button>
</div>
</div>
</section>